name: Wait_test

on:
  push:
    branches: master
  workflow_run:
    workflows: Echo_something
    types: 
      - completed
      
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Yes"
